/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CmsRouteImport } from './routes/cms'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CmsUsersRouteImport } from './routes/cms.users'
import { Route as CmsTechnologiesRouteImport } from './routes/cms.technologies'
import { Route as CmsDashboardRouteImport } from './routes/cms.dashboard'
import { Route as CmsCategoriesRouteImport } from './routes/cms.categories'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPricingRouteImport } from './routes/_app.pricing'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCreateRouteImport } from './routes/_app.create'
import { Route as AppBrowseRouteImport } from './routes/_app.browse'
import { Route as CmsProjectsIndexRouteImport } from './routes/cms.projects.index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app.projects.index'
import { Route as CmsProjectsNewRouteImport } from './routes/cms.projects.new'
import { Route as CmsProjectsIdRouteImport } from './routes/cms.projects.$id'
import { Route as AppProjectsIdRouteImport } from './routes/_app.projects.$id'

const CmsRoute = CmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsUsersRoute = CmsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => CmsRoute,
} as any)
const CmsTechnologiesRoute = CmsTechnologiesRouteImport.update({
  id: '/technologies',
  path: '/technologies',
  getParentRoute: () => CmsRoute,
} as any)
const CmsDashboardRoute = CmsDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CmsRoute,
} as any)
const CmsCategoriesRoute = CmsCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => CmsRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingRoute = AppPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const AppBrowseRoute = AppBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AppRoute,
} as any)
const CmsProjectsIndexRoute = CmsProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => CmsRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const CmsProjectsNewRoute = CmsProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => CmsRoute,
} as any)
const CmsProjectsIdRoute = CmsProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => CmsRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cms': typeof CmsRouteWithChildren
  '/browse': typeof AppBrowseRoute
  '/create': typeof AppCreateRoute
  '/dashboard': typeof AppDashboardRoute
  '/pricing': typeof AppPricingRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/cms/categories': typeof CmsCategoriesRoute
  '/cms/dashboard': typeof CmsDashboardRoute
  '/cms/technologies': typeof CmsTechnologiesRoute
  '/cms/users': typeof CmsUsersRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/cms/projects/$id': typeof CmsProjectsIdRoute
  '/cms/projects/new': typeof CmsProjectsNewRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/cms/projects/': typeof CmsProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cms': typeof CmsRouteWithChildren
  '/browse': typeof AppBrowseRoute
  '/create': typeof AppCreateRoute
  '/dashboard': typeof AppDashboardRoute
  '/pricing': typeof AppPricingRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/cms/categories': typeof CmsCategoriesRoute
  '/cms/dashboard': typeof CmsDashboardRoute
  '/cms/technologies': typeof CmsTechnologiesRoute
  '/cms/users': typeof CmsUsersRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/cms/projects/$id': typeof CmsProjectsIdRoute
  '/cms/projects/new': typeof CmsProjectsNewRoute
  '/projects': typeof AppProjectsIndexRoute
  '/cms/projects': typeof CmsProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/cms': typeof CmsRouteWithChildren
  '/_app/browse': typeof AppBrowseRoute
  '/_app/create': typeof AppCreateRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/pricing': typeof AppPricingRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/cms/categories': typeof CmsCategoriesRoute
  '/cms/dashboard': typeof CmsDashboardRoute
  '/cms/technologies': typeof CmsTechnologiesRoute
  '/cms/users': typeof CmsUsersRoute
  '/_app/projects/$id': typeof AppProjectsIdRoute
  '/cms/projects/$id': typeof CmsProjectsIdRoute
  '/cms/projects/new': typeof CmsProjectsNewRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/cms/projects/': typeof CmsProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cms'
    | '/browse'
    | '/create'
    | '/dashboard'
    | '/pricing'
    | '/profile'
    | '/settings'
    | '/auth/callback'
    | '/cms/categories'
    | '/cms/dashboard'
    | '/cms/technologies'
    | '/cms/users'
    | '/projects/$id'
    | '/cms/projects/$id'
    | '/cms/projects/new'
    | '/projects/'
    | '/cms/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cms'
    | '/browse'
    | '/create'
    | '/dashboard'
    | '/pricing'
    | '/profile'
    | '/settings'
    | '/auth/callback'
    | '/cms/categories'
    | '/cms/dashboard'
    | '/cms/technologies'
    | '/cms/users'
    | '/projects/$id'
    | '/cms/projects/$id'
    | '/cms/projects/new'
    | '/projects'
    | '/cms/projects'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/cms'
    | '/_app/browse'
    | '/_app/create'
    | '/_app/dashboard'
    | '/_app/pricing'
    | '/_app/profile'
    | '/_app/settings'
    | '/auth/callback'
    | '/cms/categories'
    | '/cms/dashboard'
    | '/cms/technologies'
    | '/cms/users'
    | '/_app/projects/$id'
    | '/cms/projects/$id'
    | '/cms/projects/new'
    | '/_app/projects/'
    | '/cms/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CmsRoute: typeof CmsRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cms': {
      id: '/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof CmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms/users': {
      id: '/cms/users'
      path: '/users'
      fullPath: '/cms/users'
      preLoaderRoute: typeof CmsUsersRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/technologies': {
      id: '/cms/technologies'
      path: '/technologies'
      fullPath: '/cms/technologies'
      preLoaderRoute: typeof CmsTechnologiesRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/dashboard': {
      id: '/cms/dashboard'
      path: '/dashboard'
      fullPath: '/cms/dashboard'
      preLoaderRoute: typeof CmsDashboardRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/categories': {
      id: '/cms/categories'
      path: '/categories'
      fullPath: '/cms/categories'
      preLoaderRoute: typeof CmsCategoriesRouteImport
      parentRoute: typeof CmsRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing': {
      id: '/_app/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AppPricingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create': {
      id: '/_app/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/browse': {
      id: '/_app/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AppBrowseRouteImport
      parentRoute: typeof AppRoute
    }
    '/cms/projects/': {
      id: '/cms/projects/'
      path: '/projects'
      fullPath: '/cms/projects/'
      preLoaderRoute: typeof CmsProjectsIndexRouteImport
      parentRoute: typeof CmsRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/cms/projects/new': {
      id: '/cms/projects/new'
      path: '/projects/new'
      fullPath: '/cms/projects/new'
      preLoaderRoute: typeof CmsProjectsNewRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/projects/$id': {
      id: '/cms/projects/$id'
      path: '/projects/$id'
      fullPath: '/cms/projects/$id'
      preLoaderRoute: typeof CmsProjectsIdRouteImport
      parentRoute: typeof CmsRoute
    }
    '/_app/projects/$id': {
      id: '/_app/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBrowseRoute: typeof AppBrowseRoute
  AppCreateRoute: typeof AppCreateRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPricingRoute: typeof AppPricingRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppProjectsIdRoute: typeof AppProjectsIdRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBrowseRoute: AppBrowseRoute,
  AppCreateRoute: AppCreateRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPricingRoute: AppPricingRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppProjectsIdRoute: AppProjectsIdRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CmsRouteChildren {
  CmsCategoriesRoute: typeof CmsCategoriesRoute
  CmsDashboardRoute: typeof CmsDashboardRoute
  CmsTechnologiesRoute: typeof CmsTechnologiesRoute
  CmsUsersRoute: typeof CmsUsersRoute
  CmsProjectsIdRoute: typeof CmsProjectsIdRoute
  CmsProjectsNewRoute: typeof CmsProjectsNewRoute
  CmsProjectsIndexRoute: typeof CmsProjectsIndexRoute
}

const CmsRouteChildren: CmsRouteChildren = {
  CmsCategoriesRoute: CmsCategoriesRoute,
  CmsDashboardRoute: CmsDashboardRoute,
  CmsTechnologiesRoute: CmsTechnologiesRoute,
  CmsUsersRoute: CmsUsersRoute,
  CmsProjectsIdRoute: CmsProjectsIdRoute,
  CmsProjectsNewRoute: CmsProjectsNewRoute,
  CmsProjectsIndexRoute: CmsProjectsIndexRoute,
}

const CmsRouteWithChildren = CmsRoute._addFileChildren(CmsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CmsRoute: CmsRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
